---
title: "Regularized Regression in Caret"
author: "Cory Costello"
date: "January 24, 2018"
output: 
  md_document:
    preserve_yaml: true
    toc: true
    toc_depth: 2
---

This is intended to provide a (very brief) introduction to some key concepts in Machine Learning/Predictive Modeling, and how they work within a regression context. Regularized regression is a nice place for folks with a psych background to start, because its an extension of the familiar regression models we've all come to know and love.

Regression models, of course, are used when you have a *continuous* outcome. So many of our problems in psych involve continuous outcomes (e.g., personality dimensions, emotions/affect, etc.), and so regression models are pretty useful for psychologists. 

But, before we dive into regularized regression, we should first cover some basic concepts in machine learning.

# The Bias-Variance Tradeoff, Overfitting, and Cross-Validation

## Bias-Variance Tradeoff

This came up briefly last week, but the bias-variance tradeoff is really crucial to everything we'll talk about today. The basic idea is that you can partition error into two components: bias and variance. **Bias** refers to the extent to which a model produces parameter estimates that miss in a particular direction (e.g., consistently over-estimating or consistently under-estimating a parameter value). **Variance** refers to the extent to which a model produces parameter estimates that vary from their central tendency across different datasets. 

There is a tradeoff between bias and variance: all else equal, increasing bias will decrease variance. The basic idea here is that if we have a zero-bias estimator, it will tend to try to fit everything in the data, whereas an estimator biased in some direction won't. This isn't to say that bias is good or bad, just that there are times where we might want to increase bias to decrease variance. As we'll see later, regularization is basically one method for introducing bias (to minimize variance).

## Overfitting 

This is probably familiar to folks in here (and it came up last week), so I won't say much about it here. The basic idea is that any data has signal and noise. Sometimes, something appears to be signal but is actually noise. That is, when our statistical models are searching for the best solution, they sometimes will be fooled into thinking some noise is signal. This is usually called **overfitting**, and it has presented a pretty substantial problem in statistical modeling. As you'll see, one of our goals is to try to avoid overfitting. Also worth noting is that overfitting will tend to produce a model with high variance, because noise will vary from dataset to dataset (basically by definition), and so a model which has fit noise will not do well across different datasets (with different noise).

## Cross-Validation

Cross-validation generally refers to taking a model that you trained on some data and using it in a new dataset. Unlike a replication, the model parameters carry over from the training to the test data (i.e., you don't simply use the same variables and re-estimate the model parameters; you save the model parameters, and use it to predict the outcome variable). You can use cross-validation both to train and evaluate a model. A simple example may make this clear.

Let's say we think home size (in square-feet) is the only relevant predictor for house price. So, we have some data on prices of recently sold houses, and estimate a model predicting house price from square-feet:

$$y_{price} = b_0 + b_1*sqaurefeet$$

Let's say we get these parameter values:

$$y_{price} = 100 + 50*sqaurefeet$$

And now we want to cross-validate in a hold-out sample. We wouldn't simply estimate this model again:

$$y_{price} = b_0 + b_1*sqaurefeet$$

We would instead apply this model:

$$y_{price} = 100 + 50*sqaurefeet$$
And evaluate how well it did. We could do this either by how much it misses, which is usually done with root mean squared error (RMSE):

$$MSE = \frac{1}{n}\sum\limits_{i=1}^{n}(y_i - \hat{y_i})^2$$
$$RMSE = \sqrt{MSE}$$

Typically, people will also look at prediction accuracy, using the model's $R^2$. This is interpreted the same way as $R^2$ always is (as the % of variance in the outcome accounted for by the model).


### K-fold cross-validation

There are different varieties of cross-validation. The most intuitive version is to create a single partition of data (i.e., split full data frame into two dataframes: training and test). However, there are other methods for cross-validation. One that has been gaining steam (or is maybe already at full steam at this point) is **k-fold cross-validation**. The basic idea is that we split a dataset into k subsamples (called folds). We then treat one subsample as the holdout sample, train on the remaining subsamples, and cross-validate on the holdout sample; then rinse and repeat so to speak. An example will probably help here.

Let's take a ridiculously simple example (based on the earlier example). We want to predict house sale price from square footage:

$$y_{price} = b_0 + b_1*sqaurefeet$$

Let's say we have just 30 cases, and we use 10-fold cross validation. Let each observation be indicated by $o_i$, so the first observation is $o_1$, the second is $o_2$, and the third is $o_3$, etc. 

First, we would fit a model using folds 2 through 10 (i.e., $o_4$ to $o_30$), and then test it on the first fold ($o_1$ to $o_3$). Then, we would fit the model using folds 1 and 3-10 (i.e., $o_1$ to $o_3$ & $o_7$ to $o_30$) and test it on the 2nd fold ($o_4$, $o_5$, $o_6$), and so on until each fold was used as the holdout sample.

Then, we calculate the average performance across all of the tests.

Note that you can also use k-fold cross-validation for training purposes. Basically, this works by taking the best fitting model from a k-fold cross-validation procedure, and then testing it on a new holdout sample. 


# Regularization

Now let's get to regularized regression. This is a pretty simple extension of OLS regression. The logic of it is basically that OLS regression is minimally biased, but because of this, is higher variance than we might want. So, the solution is to introduce some bias into the model that will decrease variance. This takes the form of a new *penalization*, which tends to either be focused on parameter size, number of parameters, or both. Let's start with the first. I find it helpful to think of these as having different beliefs, and choosing one depends on whether or not those beliefs seem correct.

## Ridge: all of these features matter, but only a little bit.

Ridge regression is basically OLS regression with an extra term. As a refresher, OLS seeks to minimize the sum of squared error, or:

$$SSE = \sum\limits_{i=1}^n = (y_i - y_i)^2$$

Ridge adds an additional penalty:

$$SSE_{L2} = \sum\limits_{i=1}^n = (y_i - y_i^2) + \lambda \sum\limits_{j=1}^p \beta^2_j$$
This makes it so that paramter values are only allowed to be large if they reduce error enough to justify their size. Functionally, this makes it so every parameter value is shrunk towards 0. You can hopefully see this in that as our paramater values (our betas) increase in size, error increases (since that we are adding the sum of squared beta values, times some constant $\lambda$, to our error term SSE). So, unless the larger parameter values decrease the first part of the error term (the ordinary sum of squared error; to the left of our new penalty), they are shrunk toward 0. 

The extent to which they are shrunk towards 0 depends on the value of $\lambda$; higher values lead to more shrinkage than lower values. This is called a *hyperparameter* because it's a parameter that governs other parameters. You can think of $\lambda$ as sort of the cost associated with larger parameter values: higher values of lambda are like telling your model that larger parameter values are more costly (so don't make them large for nothing).

Finally, you can think of this penalty as introducing a specific type of bias: bias towards smaller parameter value. However, since larger parameter values can result from overfitting, this bias can result in reducing variance.